//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneNetwork.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallsView
    {
        public int IdNumber { get; set; }
        public int IdSubscriber { get; set; }
        public string NumberName { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<int> IdTariffPlan { get; set; }
        public decimal Balance { get; set; }
        public string StatusCode { get; set; }
        public int IdCalls { get; set; }
        public int IdInNumber { get; set; }
        public System.DateTime CallsDate { get; set; }
        public int DurationInMinute { get; set; }
        public int IdOutNumber { get; set; }
    }
}
