//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneNetwork.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int IdCalls { get; set; }
        public System.DateTime CallsDate { get; set; }
        public int DurationInMinute { get; set; }
        public int IdIn { get; set; }
        public int IdOut { get; set; }
    
        public virtual Number Number { get; set; }
        public virtual Number Number1 { get; set; }
    }
}
