//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneNetwork.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int IdCalls { get; set; }
        public int IdNumber { get; set; }
        public System.DateTime CallsDate { get; set; }
        public int DurationInMinute { get; set; }
        public string CompanionNumber { get; set; }
        public string DirectionCode { get; set; }
        public decimal CostOfMinute { get; set; }
        public decimal CostCalls { get; set; }
        public int IdCheque { get; set; }
    
        public virtual Cheque Cheque { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Number Number { get; set; }
    }
}
