//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneNetwork.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberView
    {
        public int IdNumber { get; set; }
        public decimal Balance { get; set; }
        public string NumberName { get; set; }
        public System.DateTime RegDate { get; set; }
        public string TariffName { get; set; }
        public bool IsDeleted { get; set; }
        public decimal Cost { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int IdSubscriber { get; set; }
        public string StatusCode { get; set; }
        public int IdTariffPlan { get; set; }
    }
}
