//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneNetwork.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Number()
        {
            this.Calls = new HashSet<Calls>();
            this.Calls1 = new HashSet<Calls>();
        }
    
        public int IdNumber { get; set; }
        public int IdSubscriber { get; set; }
        public string NumberName { get; set; }
        public System.DateTime RegDate { get; set; }
        public int IdTariffPlan { get; set; }
        public decimal Balance { get; set; }
        public string StatusCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calls> Calls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calls> Calls1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        public virtual TariffPlan TariffPlan { get; set; }
    }
}
